"""Description of the migration

Revision ID: a2d7766d23e4
Revises: 
Create Date: 2023-09-24 21:42:52.548216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2d7766d23e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_in_y', sa.Integer(), nullable=True),
    sa.Column('check_in_m', sa.Integer(), nullable=True),
    sa.Column('check_in_d', sa.Integer(), nullable=True),
    sa.Column('check_out_y', sa.Integer(), nullable=True),
    sa.Column('check_out_m', sa.Integer(), nullable=True),
    sa.Column('check_out_d', sa.Integer(), nullable=True),
    sa.Column('chk_in_full', sa.String(length=125), nullable=True),
    sa.Column('chk_out_full', sa.String(length=125), nullable=True),
    sa.Column('total_days', sa.Integer(), nullable=True),
    sa.Column('reserved_by', sa.Integer(), nullable=True),
    sa.Column('reserved_by_user', sa.String(length=125), nullable=True),
    sa.Column('reserved_room', sa.Integer(), nullable=True),
    sa.Column('reserved_room_title', sa.String(length=125), nullable=True),
    sa.Column('reserved_room_thumb', sa.String(length=125), nullable=True),
    sa.Column('reserved_room_price', sa.String(length=125), nullable=True),
    sa.Column('expire_date', sa.String(length=125), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_earning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('today_date', sa.String(length=125), nullable=True),
    sa.Column('earning', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dashboard_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_earning', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=225), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumb', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('bed', sa.Integer(), nullable=True),
    sa.Column('lunch', sa.Integer(), nullable=True),
    sa.Column('wifi', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=150), nullable=True),
    sa.Column('lname', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('avatar', sa.String(length=225), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('zip_code', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('registered_on', sa.String(length=25), nullable=True),
    sa.Column('hashCode', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('rooms')
    op.drop_table('dashboard_info')
    op.drop_table('daily_earning')
    op.drop_table('booking')
    # ### end Alembic commands ###
